### ISSUE TITLE
Z3 Path

### ISSUE THREAD

**Issue by pantrombka** [CERTCC/kaiju#15]
Where I should add z3 jar library?
I have a problem with error:
021-12-30 15:06:43 ERROR (EventManager) Plugin Event Error: Error in plugin event listener java.lang.NoClassDefFoundError: Could not initialize class com.microsoft.z3.Native
	at com.microsoft.z3.Version.getFullVersion(Version.java:71)
	at kaiju.tools.ghihorn.GhiHornProvider.buildAnalysisControlPanel(GhiHornProvider.java:289)
	at kaiju.tools.ghihorn.GhiHornProvider.buildMainPanel(GhiHornProvider.java:584)
	at kaiju.tools.ghihorn.GhiHornProvider.<init>(GhiHornProvider.java:154)
	at kaiju.tools.ghihorn.GhiHornPlugin.programActivated(GhiHornPlugin.java:172)
	at ghidra.app.plugin.ProgramPlugin.processEvent(ProgramPlugin.java:138)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireActivatedEvent(MultiProgramManager.java:281)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:254)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:196)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:96)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:473)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:232)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openProgram(ProgramManagerPlugin.java:479)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openPrograms(ProgramManagerPlugin.java:666)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.acceptData(ProgramManagerPlugin.java:130)
	at ghidra.framework.plugintool.PluginManager.acceptData(PluginManager.java:48)
	at ghidra.framework.plugintool.PluginTool.acceptDomainFiles(PluginTool.java:414)
	at ghidra.framework.main.ToolButton.openDomainFiles(ToolButton.java:647)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:625)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
  
GhiHorn panel show 'Z3 not found' message

**Comment by Jonathan-Greve** [comment]
For me it worked by copying it to the folder with ghidraRun.bat on my Windows machine.

**Comment by sei-eschwartz** [comment]
This is probably something we should have in the documentation.

**Comment by sei-gwassermann** [comment]
Thanks @Jonathan-Greve I've added a note about this to the README to help future users. Will need to investigate a more automated way of handling this but at least there's some tips for now! This change should be in the next bugfix release getting pushed later today so I will close this.
