### ISSUE TITLE
When GhiHorn extension active, opening AArch64 binary causes hundreds of errors, hanging UI

### ISSUE THREAD

**Issue by goo99x** [CERTCC/kaiju#25]
After a program has been analyzed, enabling GhiHorn plugin and opening the program leads to multiple errors which hijack the UI.

Here is an image of what the UI looks like:
![image](https://user-images.githubusercontent.com/106996242/181628672-111ba33c-97a3-4a16-a00b-45c746b7f4fe.png)
Notice the black rim of the dialogs overlapping as I suspect hundreds are being created. The only solution is to kill ghidra with SIGTERM (SIGKILL not required so some signal handling is working).

- Ghidra 10.1.3
- Kaiju 10.1.3 release
- Z3 same as release's Z3 java jar (4.8.14.0)
- System: Ubuntu 22.04

BINARY: [binary.zip](https://github.com/CERTCC/kaiju/files/9213886/binary.zip)

**Comment by sei-eschwartz** [comment]
Can you ever see what the warnings are?

**Comment by goo99x** [comment]
> Can you ever see what the warnings are?

Unfortunately not. Is there a log file that I could look at instead of the UI to give you more information?

**Comment by edmcman** [comment]
Yes, look for `application.log`.  The location depends on your OS.  On Linux, it's in `~/.ghidra_VERSION/application.log`.

**Comment by sei-gwassermann** [comment]
Thanks @goo99x ! This is a problem with the hashing analysis tool that should get fixed in a public release soon. In the meantime, it's not actually necessary for using GhiHorn, so you can disable it (uncheck the box) in the AutoAnalysis window as a workaround for now if you don't need that functionality.

**Comment by wideglide** [comment]
I have a very similar issue on Mac with a different error:

```java
2023-01-11 17:31:26 ERROR (FnHashAnalyzer) Error while computing function hashes java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.num_basic_blocks" is null
        at kaiju.hashing.FnHashSaveable.save(FnHashSaveable.java:208)
        at ghidra.program.database.properties.ObjectPropertyMapDB.add(ObjectPropertyMapDB.java:269)
        at kaiju.tools.fnhash.FnHashAnalyzer.added(FnHashAnalyzer.java:180)
        at ghidra.app.plugin.core.analysis.AnalysisScheduler.runAnalyzer(AnalysisScheduler.java:186)
        at ghidra.app.plugin.core.analysis.AnalysisTask.applyTo(AnalysisTask.java:39)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager$AnalysisTaskWrapper.run(AutoAnalysisManager.java:688)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:788)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
        at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
        at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
        at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
        at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by sei-gwassermann** [comment]
Thanks @wideglide for the report. I didn't do error checking as much as I should have here. Let me work on fixing that ASAP.
