### ISSUE TITLE
Bundled Z3 in Linux release does not work

### ISSUE THREAD

**Issue by sei-eschwartz** [CERTCC/kaiju#48]
**Describe the bug**
When installing from release 230921, the Kaiju menu contains "GhiHorn is missing z3".

**To Reproduce**
1. Install Linux
2. Install the .zip extension from release 230921.
3. Start Ghidra
4. Open code browser
5. Look at Kaiju menu items
6. See problem

**Expected behavior**
I expected z3 to be found since it's included in the extension zip file.

**Screenshots**

**Comment by sei-eschwartz** [comment]
Probably the same as #44

**Comment by sei-eschwartz** [comment]
I added some logging

```
2023-09-21 17:11:50 WARN  (GhiHornPlugin) Error while loading Z3 libraries: no libz3java in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib java.lang.UnsatisfiedLi
nkError: no libz3java in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2429)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1989)
        at com.microsoft.z3.Native.<clinit>(Native.java:17)
        at com.microsoft.z3.Version.getFullVersion(Version.java:71)
        at kaiju.tools.ghihorn.GhiHornPlugin.<clinit>(GhiHornPlugin.java:88)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:467)
        at ghidra.util.classfinder.ClassFinder.loadExtensionPoint(ClassFinder.java:121)
        at ghidra.util.classfinder.ClassJar.processClassFiles(ClassJar.java:177)
        at ghidra.util.classfinder.ClassJar.scanJar(ClassJar.java:83)
        at ghidra.util.classfinder.ClassJar.<init>(ClassJar.java:60)
        at ghidra.util.classfinder.ClassFinder.initialize(ClassFinder.java:66)
        at ghidra.util.classfinder.ClassFinder.<init>(ClassFinder.java:44)
        at ghidra.util.classfinder.ClassSearcher.search(ClassSearcher.java:259)
        at ghidra.framework.HeadlessGhidraApplicationConfiguration.performClassSearching(HeadlessGhidraApplicationConfiguration.java:76)
        at ghidra.framework.HeadlessGhidraApplicationConfiguration.initializeApplication(HeadlessGhidraApplicationConfiguration.java:40)
        at ghidra.framework.GhidraApplicationConfiguration.initializeApplication(GhidraApplicationConfiguration.java:56)
        at ghidra.framework.Application.initializeApplication(Application.java:115)
        at ghidra.GhidraRun.lambda$launch$1(GhidraRun.java:74)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

Eventually this gets punted to the Java loader, which doesn't know anything about the Ghidra extension directories.  But presumably some of the ghidra.util.classfinder stuff should know better?

**Comment by sei-eschwartz** [comment]
In z3:
``` java
  static {
    if (!Boolean.parseBoolean(System.getProperty("z3.skipLibraryLoad"))) {
      try {
        System.loadLibrary("z3java");
      } catch (UnsatisfiedLinkError ex) {
        System.loadLibrary("libz3java");
      }
    }
  }
  ```

So I have a better idea what is going on now.  Kaiju loads the .so files from the right place, but then Z3 goes ahead and reloads them, and doesn't find them in the standard paths.

**Comment by sei-eschwartz** [comment]
Sweet, I fixed it:

https://github.com/CERTCC/kaiju/pull/49/commits/46b44bafa245dad82cb686de276adfaa4445d2a1
