### ISSUE TITLE
Test binary builds with Z3, and update documentation

### ISSUE THREAD

**Issue by sei-eschwartz** [CERTCC/kaiju#6]

**Comment by sei-eschwartz** [comment]
```
no libz3java in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
java.lang.UnsatisfiedLinkError: no libz3java in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2423)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:808)
	at java.base/java.lang.System.loadLibrary(System.java:1893)
	at com.microsoft.z3.Native.<clinit>(Native.java:17)
	at com.microsoft.z3.Version.getFullVersion(Version.java:71)
	at kaiju.tools.ghihorn.GhiHornProvider.buildAnalysisControlPanel(GhiHornProvider.java:292)
	at kaiju.tools.ghihorn.GhiHornProvider.buildMainPanel(GhiHornProvider.java:572)
	at kaiju.tools.ghihorn.GhiHornProvider.<init>(GhiHornProvider.java:157)
	at kaiju.tools.ghihorn.GhiHornPlugin.programActivated(GhiHornPlugin.java:172)
	at ghidra.app.plugin.ProgramPlugin.processEvent(ProgramPlugin.java:138)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:329)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:475)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:481)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireActivatedEvent(MultiProgramManager.java:278)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:251)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.setCurrentProgram(MultiProgramManager.java:193)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:93)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:489)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.util.SystemUtilities.runSwingNow(SystemUtilities.java:232)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openProgram(ProgramManagerPlugin.java:495)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openPrograms(ProgramManagerPlugin.java:781)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.acceptData(ProgramManagerPlugin.java:139)
	at ghidra.framework.plugintool.PluginManager.acceptData(PluginManager.java:48)
	at ghidra.framework.plugintool.PluginTool.acceptDomainFiles(PluginTool.java:414)
	at ghidra.framework.main.ToolButton.openDomainFiles(ToolButton.java:647)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:625)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:310)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:242)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

---------------------------------------------------
Build Date: 2021-Jul-08 1512 EDT
Ghidra Version: 10.0.1
Java Home: /usr/lib/jvm/zulu-16-amd64
JVM Version: Azul Systems, Inc. 16
OS: Linux 5.7.0-994-generic amd64
Workstation: ed-Precision-7540
```

**Comment by sei-eschwartz** [comment]
The good news is that Kaiju still works.  But we'll need to add instructions on where to add the Z3 files.

**Comment by sei-gwassermann** [comment]
We definitely have some instructions for Z3 in the README now, though still need to consider a more automated process. I think the automated testing uses Z3 now too right? Is this ticket ready to close? @sei-eschwartz

**Comment by sei-eschwartz** [comment]
I have not personally tested this, though it sounds like others have been. I would say leave it open for now and I'll try to test this next week.

Ed

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by sei-gwassermann** [comment]
The upcoming release should be able to handle building Z3 and setting up Java to load the libraries.
